# Generated by Django 4.2 on 2024-06-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_resume",
            "0002_remove_skillmodel_name_alter_educationmodel_date_end_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="skillmodel",
            name="name",
            field=models.CharField(
                default="python", max_length=50, verbose_name="name"
            ),
            preserve_default=False,
        ),
    ]
